package br.com.gabrielorander.barto.feature.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF9C432F)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDAD2)
val light_onPrimaryContainer = Color(0xFF3D0600)
val light_secondary = Color(0xFF00658D)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFC6E7FF)
val light_onSecondaryContainer = Color(0xFF001E2E)
val light_tertiary = Color(0xFF874589)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFD6FA)
val light_onTertiaryContainer = Color(0xFF37003C)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201A19)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201A19)
val light_surfaceVariant = Color(0xFFF5DDD8)
val light_onSurfaceVariant = Color(0xFF534340)
val light_outline = Color(0xFF85736F)
val light_inverseOnSurface = Color(0xFFFBEEEB)
val light_inverseSurface = Color(0xFF362F2D)
val light_inversePrimary = Color(0xFFFFB4A3)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF9C432F)
val light_outlineVariant = Color(0xFFD8C2BD)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFFFB4A3)
val dark_onPrimary = Color(0xFF5E1606)
val dark_primaryContainer = Color(0xFF7D2C1A)
val dark_onPrimaryContainer = Color(0xFFFFDAD2)
val dark_secondary = Color(0xFF83CFFF)
val dark_onSecondary = Color(0xFF00344B)
val dark_secondaryContainer = Color(0xFF004C6C)
val dark_onSecondaryContainer = Color(0xFFC6E7FF)
val dark_tertiary = Color(0xFFFBACF8)
val dark_onTertiary = Color(0xFF521457)
val dark_tertiaryContainer = Color(0xFF6D2D6F)
val dark_onTertiaryContainer = Color(0xFFFFD6FA)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201A19)
val dark_onBackground = Color(0xFFEDE0DD)
val dark_surface = Color(0xFF201A19)
val dark_onSurface = Color(0xFFEDE0DD)
val dark_surfaceVariant = Color(0xFF534340)
val dark_onSurfaceVariant = Color(0xFFD8C2BD)
val dark_outline = Color(0xFFA08C88)
val dark_inverseOnSurface = Color(0xFF201A19)
val dark_inverseSurface = Color(0xFFEDE0DD)
val dark_inversePrimary = Color(0xFF9C432F)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB4A3)
val dark_outlineVariant = Color(0xFF534340)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFF4E342E)